site_name: 9964A Program Documentation
site_description: Documentation for team 9964A's program built using the PROS library.
site_author: Eric Zhang

# github repository information
repo_name: HiddenAbilitree/9964A-PROSject
repo_url: https://github.com/HiddenAbilitree/9964A-Official-PROSject
edit_uri: ""

# new colors
extra_css:
  - stylesheets/extra.css

# theme
theme:
  features:
    - content.code.annotate
#   - navigation.tabs
    - navigation.expand
    - navigation.tracking
    - navigation.instant
    - navigation.sections
#   - navigation.indexes
    - toc.integrate
  icon:
    repo: fontawesome/brands/github

  name: material
  custom_dir: overrides
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to system preference

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  generator: false
  social: 
    - icon: fontawesome/brands/github
      link: https://github.com/HiddenAbilitree/9964A-PROSject
      name: 9964A Repository
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret:
      smart_insert: true
      insert: true
      superscript: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      auto_title: true
      linenums: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.mark:
      smart_mark: true
  - pymdownx.snippets:
      check_paths: true
      base_path: '.'
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - tables
  - toc:
      permalink: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js